# Site settings
baseurl = "http://wfernandes.cfapps.io/"
themesDir = "./themes"
languageCode = "en-us"
title = "Warren's Simple Blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Warren Fernandes"
	description = "I'm not sure what I want to blog about..."
	bio = "Blogger - Engineer - Gopher"
	# Enter optionally your twitter account
	twitter = "warren_ff"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm an enthusiastic engineer who likes to solve meaningful problems."
	tweet = ""
	share = ""
	# 404 page
	title404 = "Oopsy Daisy..."
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/warren_ff"
    facebook = "https://www.facebook.com/warren.f.fernandes"
    github   = "https://www.github.com/wfernandes"
