# Site settings
baseURL = "https://wfernandes.github.io/"
publishDir = "wfernandes.github.io"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "vim"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "·Warren Fernandes·"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Warren Fernandes"
  email = "warren.f.fernandes@gmail.com"
  description = "Landing Page"
  bio = "Passion Perseverance Patience Practice Purpose"
  avatar = "img/profile.jpeg"
  favicon = "img/favicon.ico"
  error404 = "As you like it!"

  [params.contact]
    github = "https://github.com/wfernandes"
    instagram = "https://instagram.com/ferna8ec"
    twitter = "https://twitter.com/warren_ff"
    linkedin = "https://www.linkedin.com/in/warrenfernandes/"
